from collections.abc import Awaitable
from typing import Any

sync: Any = ...
window: Any = ...
workers: dict[str, Awaitable[PyWorker]] = ...

class PyWorker:
    sync: Any = ...
    def __init__(self, file: str) -> None: ...
    @property
    async def ready(self) -> bool: ...
